const ImmunizationCodes = [
  {
    system: "http://hl7.org/fhir/sid/cvx",
    values: [
      { code: "143", display: "Adenovirus types 4 and 7" },
      { code: "54", display: "adenovirus, type 4" },
      { code: "55", display: "adenovirus, type 7" },
      { code: "82", display: "adenovirus, unspecified formulation" },
      { code: "24", display: "anthrax" },
      { code: "181", display: "anthrax immune globulin" },
      { code: "801", display: "AS03 Adjuvant" },
      { code: "19", display: "BCG" },
      { code: "27", display: "botulinum antitoxin" },
      { code: "173", display: "cholera, BivWC" },
      { code: "174", display: "cholera, live attenuated" },
      { code: "26", display: "cholera, unspecified formulation" },
      { code: "172", display: "cholera, WC-rBS" },
      { code: "29", display: "CMVIG" },
      { code: "56", display: "dengue fever" },
      { code: "12", display: "diphtheria antitoxin" },
      { code: "28", display: "DT (pediatric)" },
      { code: "20", display: "DTaP" },
      { code: "106", display: "DTaP, 5 pertussis antigens" },
      { code: "107", display: "DTaP, unspecified formulation" },
      { code: "146", display: "DTaP,IPV,Hib,HepB" },
      { code: "110", display: "DTaP-Hep B-IPV" },
      { code: "50", display: "DTaP-Hib" },
      { code: "120", display: "DTaP-Hib-IPV" },
      { code: "130", display: "DTaP-IPV" },
      { code: "132", display: "DTaP-IPV-HIB-HEP B, historical" },
      { code: "170", display: "DTAP/IPV/HIB - non-US" },
      { code: "01", display: "DTP" },
      { code: "22", display: "DTP-Hib" },
      { code: "102", display: "DTP-Hib-Hep B" },
      { code: "57", display: "hantavirus" },
      { code: "30", display: "HBIG" },
      { code: "52", display: "Hep A, adult" },
      { code: "154", display: "Hep A, IG" },
      { code: "169", display: "Hep A, live attenuated" },
      { code: "83", display: "Hep A, ped/adol, 2 dose" },
      { code: "84", display: "Hep A, ped/adol, 3 dose" },
      { code: "31", display: "Hep A, pediatric, unspecified formulation" },
      { code: "85", display: "Hep A, unspecified formulation" },
      { code: "104", display: "Hep A-Hep B" },
      { code: "193", display: "Hep A-Hep B, pediatric/adolescent" },
      { code: "08", display: "Hep B, adolescent or pediatric" },
      { code: "42", display: "Hep B, adolescent/high risk infant" },
      { code: "43", display: "Hep B, adult" },
      { code: "44", display: "Hep B, dialysis" },
      { code: "45", display: "Hep B, unspecified formulation" },
      { code: "58", display: "Hep C" },
      { code: "59", display: "Hep E" },
      { code: "189", display: "HepB-CpG" },
      { code: "60", display: "herpes simplex 2" },
      { code: "47", display: "Hib (HbOC)" },
      { code: "46", display: "Hib (PRP-D)" },
      { code: "49", display: "Hib (PRP-OMP)" },
      { code: "48", display: "Hib (PRP-T)" },
      { code: "17", display: "Hib, unspecified formulation" },
      { code: "51", display: "Hib-Hep B" },
      { code: "61", display: "HIV" },
      { code: "118", display: "HPV, bivalent" },
      { code: "62", display: "HPV, quadrivalent" },
      { code: "137", display: "HPV, unspecified formulation" },
      { code: "165", display: "HPV9" },
      { code: "86", display: "IG" },
      { code: "14", display: "IG, unspecified formulation" },
      { code: "87", display: "IGIV" },
      {
        code: "160",
        display: "Influenza A monovalent (H5N1), ADJUVANTED-2013",
      },
      { code: "151", display: "influenza nasal, unspecified formulation" },
      { code: "123", display: "influenza, H5N1-1203" },
      { code: "135", display: "Influenza, high dose seasonal" },
      {
        code: "153",
        display: "Influenza, injectable, MDCK, preservative free",
      },
      {
        code: "171",
        display: "Influenza, injectable, MDCK, preservative free, quadrivalent",
      },
      {
        code: "186",
        display: "Influenza, injectable, MDCK, quadrivalent, preservative",
      },
      { code: "158", display: "influenza, injectable, quadrivalent" },
      {
        code: "150",
        display: "influenza, injectable, quadrivalent, preservative free",
      },
      {
        code: "161",
        display:
          "Influenza, injectable,quadrivalent, preservative free, pediatric",
      },
      {
        code: "166",
        display: "influenza, intradermal, quadrivalent, preservative free",
      },
      { code: "111", display: "influenza, live, intranasal" },
      { code: "149", display: "influenza, live, intranasal, quadrivalent" },
      {
        code: "155",
        display: "influenza, recombinant, injectable, preservative free",
      },
      {
        code: "185",
        display:
          "influenza, recombinant, quadrivalent,injectable, preservative free",
      },
      { code: "141", display: "Influenza, seasonal, injectable" },
      {
        code: "140",
        display: "Influenza, seasonal, injectable, preservative free",
      },
      {
        code: "144",
        display: "influenza, seasonal, intradermal, preservative free",
      },
      {
        code: "15",
        display: "influenza, split (incl. purified surface antigen)",
      },
      { code: "168", display: "influenza, trivalent, adjuvanted" },
      { code: "88", display: "influenza, unspecified formulation" },
      { code: "16", display: "influenza, whole" },
      { code: "10", display: "IPV" },
      { code: "134", display: "Japanese Encephalitis IM" },
      { code: "39", display: "Japanese encephalitis SC" },
      {
        code: "129",
        display: "Japanese Encephalitis, unspecified formulation",
      },
      { code: "63", display: "Junin virus" },
      { code: "64", display: "leishmaniasis" },
      { code: "65", display: "leprosy" },
      { code: "66", display: "Lyme disease" },
      { code: "04", display: "M/R" },
      { code: "67", display: "malaria" },
      { code: "05", display: "measles" },
      { code: "68", display: "melanoma" },
      { code: "191", display: "meningococcal A polysaccharide (non-US)" },
      { code: "192", display: "meningococcal AC polysaccharide (non-US)" },
      { code: "108", display: "meningococcal ACWY, unspecified formulation" },
      { code: "163", display: "meningococcal B, OMV" },
      { code: "162", display: "meningococcal B, recombinant" },
      { code: "164", display: "meningococcal B, unspecified" },
      { code: "103", display: "meningococcal C conjugate" },
      { code: "148", display: "Meningococcal C/Y-HIB PRP" },
      { code: "147", display: "meningococcal MCV4, unspecified formulation" },
      { code: "136", display: "Meningococcal MCV4O" },
      { code: "114", display: "meningococcal MCV4P" },
      { code: "32", display: "meningococcal MPSV4" },
      { code: "167", display: "meningococcal, unknown serogroups" },
      { code: "03", display: "MMR" },
      { code: "94", display: "MMRV" },
      { code: "07", display: "mumps" },
      { code: "127", display: "Novel influenza-H1N1-09" },
      { code: "128", display: "Novel Influenza-H1N1-09, all formulations" },
      { code: "125", display: "Novel Influenza-H1N1-09, nasal" },
      { code: "126", display: "Novel influenza-H1N1-09, preservative-free" },
      { code: "02", display: "OPV" },
      { code: "179", display: "OPV ,monovalent, unspecified" },
      { code: "178", display: "OPV bivalent" },
      { code: "182", display: "OPV, Unspecified" },
      { code: "69", display: "parainfluenza-3" },
      { code: "177", display: "PCV10" },
      { code: "11", display: "pertussis" },
      { code: "23", display: "plague" },
      { code: "133", display: "Pneumococcal conjugate PCV 13" },
      { code: "100", display: "pneumococcal conjugate PCV 7" },
      {
        code: "152",
        display: "Pneumococcal Conjugate, unspecified formulation",
      },
      { code: "33", display: "pneumococcal polysaccharide PPV23" },
      { code: "109", display: "pneumococcal, unspecified formulation" },
      { code: "89", display: "polio, unspecified formulation" },
      { code: "70", display: "Q fever" },
      { code: "175", display: "Rabies - IM Diploid cell culture" },
      { code: "176", display: "Rabies - IM fibroblast culture" },
      { code: "40", display: "rabies, intradermal injection" },
      { code: "18", display: "rabies, intramuscular injection" },
      { code: "90", display: "rabies, unspecified formulation" },
      { code: "72", display: "rheumatic fever" },
      { code: "159", display: "Rho(D) - Unspecified formulation" },
      { code: "157", display: "Rho(D) -IG IM" },
      { code: "156", display: "Rho(D)-IG" },
      { code: "73", display: "Rift Valley fever" },
      { code: "34", display: "RIG" },
      { code: "119", display: "rotavirus, monovalent" },
      { code: "116", display: "rotavirus, pentavalent" },
      { code: "74", display: "rotavirus, tetravalent" },
      { code: "122", display: "rotavirus, unspecified formulation" },
      { code: "71", display: "RSV-IGIV" },
      { code: "93", display: "RSV-MAb" },
      { code: "145", display: "RSV-MAb (new)" },
      { code: "06", display: "rubella" },
      { code: "38", display: "rubella/mumps" },
      { code: "76", display: "Staphylococcus bacterio lysate" },
      { code: "138", display: "Td (adult)" },
      {
        code: "09",
        display: "Td (adult), 2 Lf tetanus toxoid, preservative free, adsorbed",
      },
      {
        code: "113",
        display: "Td (adult), 5 Lf tetanus toxoid, preservative free, adsorbed",
      },
      { code: "139", display: "Td(adult) unspecified formulation" },
      { code: "115", display: "Tdap" },
      { code: "180", display: "tetanus immune globulin" },
      { code: "35", display: "tetanus toxoid, adsorbed" },
      { code: "142", display: "tetanus toxoid, not adsorbed" },
      { code: "112", display: "tetanus toxoid, unspecified formulation" },
      { code: "77", display: "tick-borne encephalitis" },
      { code: "13", display: "TIG" },
      { code: "98", display: "TST, unspecified formulation" },
      { code: "95", display: "TST-OT tine test" },
      { code: "96", display: "TST-PPD intradermal" },
      { code: "97", display: "TST-PPD tine test" },
      { code: "78", display: "tularemia vaccine" },
      { code: "190", display: "Typhoid conjugate vaccine (TCV)" },
      { code: "25", display: "typhoid, oral" },
      { code: "41", display: "typhoid, parenteral" },
      { code: "53", display: "typhoid, parenteral, AKD (U.S. military)" },
      { code: "91", display: "typhoid, unspecified formulation" },
      { code: "101", display: "typhoid, ViCPs" },
      { code: "131", display: "typhus, historical" },
      { code: "75", display: "vaccinia (smallpox)" },
      { code: "105", display: "vaccinia (smallpox) diluted" },
      { code: "79", display: "vaccinia immune globulin" },
      { code: "21", display: "varicella" },
      { code: "81", display: "VEE, inactivated" },
      { code: "80", display: "VEE, live" },
      { code: "92", display: "VEE, unspecified formulation" },
      { code: "36", display: "VZIG" },
      { code: "117", display: "VZIG (IND)" },
      { code: "37", display: "yellow fever" },
      { code: "183", display: "Yellow fever vaccine - alt" },
      { code: "184", display: "Yellow fever, unspecified formulation" },
      { code: "121", display: "zoster live" },
      { code: "187", display: "zoster recombinant" },
      { code: "188", display: "zoster, unspecified formulation" },
      { code: "998", display: "no vaccine administered" },
      { code: "99", display: "RESERVED - do not use" },
      { code: "999", display: "unknown" },
    ],
  },
  {
    system: "urn:oid:1.2.36.1.2001.1005.17",
    values: [
      { code: "AGRPAL", display: "Agrippal" },
      { code: "AVAXM", display: "Avaxim" },
      { code: "BCG", display: "BCG" },
      { code: "CDT", display: "CDT" },
      { code: "CMX", display: "COMVAX" },
      { code: "DTP", display: "Triple Antigen" },
      { code: "DTPA", display: "DTPa" },
      { code: "ENGP", display: "Engerix B" },
      { code: "FLRIX", display: "Fluarix" },
      { code: "FLUVAX", display: "Fluvax" },
      { code: "FLVRN", display: "Fluvirin" },
      { code: "FVXJNR", display: "Fluvax Junior" },
      { code: "GNDIP", display: "Diphtheria" },
      { code: "GNFLU", display: "Influenza" },
      { code: "GNHEP", display: "Hepatitis B" },
      { code: "GNHIB", display: "HIB" },
      { code: "GNHPA", display: "Hepatitis A" },
      { code: "GNJEN", display: "Japanese Encephalitis" },
      { code: "GNMEA", display: "Measles" },
      { code: "GNMEN", display: "Meningococcal C" },
      { code: "GNMUM", display: "Mumps" },
      { code: "GNPNE", display: "Pneumococcal" },
      { code: "GNPOL", display: "Polio" },
      { code: "GNROX", display: "Rotavirus" },
      { code: "GNRUB", display: "Rubella" },
      { code: "GNTET", display: "Tetanus" },
      { code: "GNVAR", display: "Varicella" },
      { code: "HATWNJ", display: "Twinrix Junior" },
      { code: "HAVAQ", display: "Vaqta Paed/Adol" },
      { code: "HAVJ", display: "Havrix Junior" },
      { code: "HBOC", display: "HibTITER" },
      { code: "HBV", display: "HBV" },
      { code: "HBVP", display: "HBVAX II" },
      { code: "HBX", display: "Hiberix" },
      { code: "IFHX", display: "Infanrix Hexa" },
      { code: "IFIP", display: "Infanrix-IPV" },
      { code: "IFPA", display: "Infanrix Penta" },
      { code: "IFX", display: "Infanrix" },
      { code: "IFXB", display: "InfanrixHepB" },
      { code: "INFLUV", display: "Influvac" },
      { code: "IPV", display: "IPOL" },
      { code: "JEVAX", display: "JE-VAX" },
      { code: "MENJUG", display: "Menjugate" },
      { code: "MENTEC", display: "Meningitec" },
      { code: "MENUME", display: "Menomune" },
      { code: "MENVAX", display: "Mencevax ACWY" },
      { code: "MMR", display: "MMR" },
      { code: "MMRCSL", display: "MMR II" },
      { code: "MMRSKB", display: "Priorix" },
      { code: "MNTRX", display: "Menitorix" },
      { code: "NEISVC", display: "NeisVac-C" },
      { code: "OPV", display: "Polio" },
      { code: "P", display: "Pertussis" },
      { code: "PANVAX", display: "Panvax" },
      { code: "PDCL", display: "Pediacel" },
      { code: "PLCL", display: "Poliacel" },
      { code: "PNEUMO", display: "Pneumovax" },
      { code: "PRPD", display: "ProHIBit" },
      { code: "PROQAD", display: "ProQuad" },
      { code: "PRPOMP", display: "PedvaxHIB" },
      { code: "PRPT", display: "ActHIB" },
      { code: "PRVNR", display: "Prevenar 7" },
      { code: "PRVTH", display: "Prevenar 13" },
      { code: "PRXTEX", display: "Priorix-Tetra" },
      { code: "QDCL", display: "Quadracel" },
      { code: "ROTRIX", display: "Rotarix" },
      { code: "ROTTEQ", display: "Rotateq" },
      { code: "SYNFLX", display: "Synflorix" },
      { code: "TCL", display: "Tripacel" },
      { code: "VAXGRP", display: "Vaxigrip" },
      { code: "VGRJNR", display: "Vaxigrip Junior" },
      { code: "VLRIX", display: "Varilrix" },
      { code: "VRVAX", display: "Varivax" },
    ],
  },
];

export function ImmunizationCodeHelper() {
  function getDisplayString(coding) {
    return (
      ImmunizationCodes.find((c) => c.system == coding.system)?.values.find(
        (c) => c.code == coding.code
      )?.display || `${coding.code} (${coding.system})`
    );
  }

  return Object.freeze({ getDisplayString });
}
